spring:
  application:
    name: client-management
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/client-management}
    username: ${DB_USERNAME:neoapp}
    password: ${DB_PASSWORD:neoapp}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  error:
    include-stacktrace: always

jwt:
  secret: ${API_SECRET:minhaChaveSuperSecretaDeNoMinimo32Caracteres}
  expiration-time: 36000000
