CREATE TABLE tb_user (
    id UUID PRIMARY KEY,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    cpf CHAR(11) UNIQUE NOT NULL,
    cell_phone VARCHAR(11) NOT NULL,
    birth_date DATE NOT NULL,
    is_Active BOOLEAN NOT NULL DEFAULT TRUE
);
